made indentation changes

diff --git a/.github/workflow/Building_blocks.yaml b/.github/workflow/Building_blocks.yaml
--- a/.github/workflow/Building_blocks.yaml
+++ b/.github/workflow/Building_blocks.yaml
@@ -3,20 +3,20 @@ on: push
 
 jobs:
   echo-hello:
-  runs_on: ubuntu-latest
-  steps:
-    -  name: Say Hello 
-       run: echo "Hello , World!"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Hello 
+        run: echo "Hello , World!"
        
   echo-goodbye:
-  runs_on: ubuntu-latest
-  steps:
-    -  name: Fail step
-       run: echo"I will fail"
-  steps: 
-    -  name: say goodbye
-       run: echo "Goodbye!"
-    -  name: failed step
-       run: |
-         echo "failed 1"
-         exit 1
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail step
+        run: echo "I will fail"
+    steps: 
+      - name: say goodbye
+        run: echo "Goodbye!"
+      - name: failed step
+        run: |
+          echo "failed 1"
+          exit 1
